"""Add datetime_reg to User

Revision ID: 2cd26e8fdda8
Revises: 94f0fa56d787
Create Date: 2024-06-16 11:59:20.016654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd26e8fdda8'
down_revision = '94f0fa56d787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_reg', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('datetime_reg')

    # ### end Alembic commands ###
