"""Make protocol not null and unique

Revision ID: 48619f815863
Revises: 3d5108156b67
Create Date: 2024-07-20 17:14:55.422218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48619f815863'
down_revision = '3d5108156b67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
