"""Add status and observation to Solicitation and user_type to User

Revision ID: 75313d026f92
Revises: 2cd26e8fdda8
Create Date: 2024-06-16 20:21:17.521753

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75313d026f92'
down_revision = '2cd26e8fdda8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitation_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('observation', sa.String(length=500), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('datetime_registration', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('datetime_reg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_reg', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_user_email', ['email'], unique=True)
        batch_op.drop_column('datetime_registration')
        batch_op.drop_column('user_type')

    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.drop_column('observation')
        batch_op.drop_column('status')

    op.drop_table('solicitation_status')
    # ### end Alembic commands ###
