"""Add SolicitationStatus table and update Solicitation table

Revision ID: c9b784bbcf4e
Revises: 75313d026f92
Create Date: 2024-06-16 20:28:29.898352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9b784bbcf4e'
down_revision = '75313d026f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'solicitation_status', ['status_id'], ['id'])
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
